project:
  type: book

book:
  title: "Strategia Tecnica â€“ Piattaforma Retail"
  author: "Tuo Nome"
  chapters:
    - index.qmd
    - introduzione.qmd

format:
  html:
    toc: true
    number-sections: true
  docx:
    toc: true
    number-sections: true
    # reference-doc: templates/brand.docx
  pdf:
    toc: true
    number-sections: true
    pdf-engine: tectonic
